service: serverlessLamda-api3
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  iam:
     role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:*'
          Resource:
            -  'arn:aws:dynamodb:us-east-1:877969058937:table/*'
 
plugins:
  - serverless-webpack

functions:
  getUser:
    handler: src/api/userApi.getUser
    events:
      - http:
          path: /items
          method: get
  addUser:
    handler: src/api/userApi.addUser
    events:
      - http:
          path: /items
          method: put
  deleteUser:
    handler: src/api/userApi.deleteUser
    events:
      - http:
          path: /items/{id}
          method: delete
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: status
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: status
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

